mushwebapp/dataclass/urls.py
from django.urls import path
from dataclass import views

app_name = 'dataclass'

urlpatterns = [
    path('', views.Dataclass.as_view(), name='dataclass'),
]

mushwebapp/imgclass/urls.py
from django.urls import path
from imgclass import views

app_name = 'imgclass'

urlpatterns = [
    path('', views.IMGclass.as_view(), name='imgclass'),
]

mushwebapp/landing/urls.py
from django.urls import path
from landing import views

app_name = 'landing'

urlpatterns = [
    path('', views.Landing.as_view(), name='landing'),
]

mushwebapp/mushinfo/urls.py
from django.urls import path
from mushinfo import views

app_name = 'mushinfo'

urlpatterns = [
    path('', views.Mushinfo.as_view(), name='mushinfo'),
]

mushwebapp/mushwebapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls', namespace='landing')),
    path('mushinfo/', include('mushinfo.urls', namespace='mushinfo')),
    path('imgclass/', include('imgclass.urls', namespace='imgclass')),
    path('dataclass/', include('dataclass.urls', namespace='dataclass'))
]

mushwebapp/dataclass/models.py
from django.db import models

# Create your models here.

mushwebapp/imgclass/models.py
from django.db import models

# Create your models here.

mushwebapp/landing/models.py
from django.db import models

# Create your models here.

mushwebapp/mushinfo/models.py
from django.db import models

# Create your models here.

mushwebapp/dataclass/views.py
import imp
from django.shortcuts import render
from django.views.generic import TemplateView

class Dataclass(TemplateView):
    template_name = 'dataclass_page.html'

mushwebapp/imgclass/views.py
import imp
from django.shortcuts import render
from django.views.generic import TemplateView

class IMGclass(TemplateView):
    template_name = 'imgclass_page.html'

mushwebapp/landing/views.py
import imp
from django.shortcuts import render
from django.views.generic import TemplateView

class Landing(TemplateView):
    template_name = 'landing_page.html'

mushwebapp/mushinfo/views.py
import imp
from django.shortcuts import render
from django.views.generic import TemplateView

class Mushinfo(TemplateView):
    template_name = 'mushinfo_page.html'

mushwebapp/dataclass/templates/dataclass_page.html
{% extends "base_tmplt.html" %}

{% block body %}

<h1>DATA classfier</h1>

{% endblock %}

mushwebapp/imgclass/templates/imgclass_page.html
{% extends "base_tmplt.html" %}

{% load static %}

{% block extrahead %}

  <link rel="stylesheet" href="{% static '/css/basestyle.css' %}">

{% endblock %}

{% block body %}

<div class="container">

     

    <div class="input-group mb-3">
        <input type="file" class="form-control" id="inputGroupFile">
        <label class="input-group-text" for="inputGroupFile">Upload</label>
    </div>  
    <hr>
    <hr>
    <div class="d-grid gap-2">
        <button class="btn btn-lg btn-secondary" type="button">Identificar</button>
      </div> 
    <hr>
    <hr>
    <div class="row g-0 border rounded overflow-hidden flex-md-row  shadow-sm  position-relative">
        <div class="col-auto d-none d-lg-block">
            <img class="" src="https://www.agromatica.es/wp-content/uploads/2014/01/Setas-Boletus-edulis.jpg" alt="Card image cap" width="700" height="450">
        </div>
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block">IDENTIFICADA</strong>
          <h3 class="mb-0">Boletus edulis</h3>
          <div class="mb-1 text-muted">COMESTIBLE</div>
          <p class="card-text mb-auto">Boletus edulis es el nombre en latín de una seta comestible, también conocida en España como1​2​ hongo blanco,3​ hongo pambazo,4​ seta calabaza, seta de calabaza o simplemente calabaza.5​ Puede encontrarse muy frecuentemente en bosques de hoja caducifolia. Es una seta que puede alcanzar dimensiones notables; por lo general el sombrero puede medir de 7 a 20 cm de diámetro y el pie adquirir la misma altura. Suele confundirse con Tylopilus felleus o con Boletus badius.

            Altamente apreciado, Boletus edulis es comercializado fresco en otoño, en el centro y sur de Europa, pero también se comercializa seco por todo el mundo. </p>
        </div>
    </div>

</div>

  
{% endblock %}

mushwebapp/landing/templates/landing_page.html
{% extends "base_tmplt.html" %}

{% load static %}

{% block extrahead %}

  <link rel="stylesheet" href="{% static '/css/basestyle.css' %}">

{% endblock %}

{% block body %}

<div class="container">

    <div class="mt-4 p-5 bg-light text-dark rounded">
        <h1>Clasificador de setas</h1>
        <p>Bienvenido a nuestra aplicación web donde podrás indagar la especie y 
            la toxicidad de las setas que encuentres en el campo mediante sus fotos o
            datos medidos in-situ
        </p>
    </div>

    <hr>

    <div id="carouselLanding" class="carousel slide z-depth-1-half" data-ride="carousel">

        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselLanding" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselLanding" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselLanding" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>

        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static "img/cesta.jpg" %}" class="d-block w-100" alt="cesta con setas">
            <div class="carousel-caption d-none d-md-block">
              <h5>Disfruta de la recolección de setas</h5>
              <p style="color:white;">Adéntrate en el bosque para buscar los especímenes más preciados</p>
            </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static "img/recolecta.jpg" %}" class="d-block w-100" alt="imagen de recolecta">
            <div class="carousel-caption d-none d-md-block">
              <h5>Conoce tus setas</h5>
              <p style="color:white;">Utiliza nuestra aplicación para identificar las setas</p>
            </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static "img/venenosas.jpg" %}" class="d-block w-100" alt="setas venenosas">
            <div class="carousel-caption d-none d-md-block">
              <h5>Consume con precaución</h5>
              <p style="color:white;">Algunas especies de setas pueden resultar muy tóxicas, ten precaución</p>
            </div>
          </div>
        </div>

    </div>

    <hr>

    <div class="row">
        <div class="col-sm-4">
          <div class="card">
            <img class="card-img-top" src="https://www.diariodesevilla.es/2020/10/23/pds/Normas-recolectar-setas-campo_1513058819_127179828_667x375.jpg" alt="Card image cap" width="200" height="200">
            <div class="card-body">
              <h5 class="card-title">Recolecta</h5>
              <p class="card-text">Anímate a disfrutar de la naturaleza y de la emoción de la búsqueda y la recolecta de las setas más preciadas.</p>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="card">
            <img class="card-img-top" src="https://www.tribunasalamanca.com/images/images/setas%281%29.jpg" alt="Card image cap" width="200" height="200">
            <div class="card-body">
              <h5 class="card-title">Identifica</h5>
              <p class="card-text">Apóyate en nuestra web para identificar correctamente las especies de setas encontradas y conocer su toxicidad.</p>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
            <div class="card">
              <img class="card-img-top" src="https://diariodegastronomia.com/wp-content/uploads/2016/10/Las-setas-en-la-cocina-a-debate-en-Soria-Gastron%C3%B3mica-759x500.jpg" alt="Card image cap" width="200" height="200">
              <div class="card-body">
                <h5 class="card-title">Consume</h5>
                <p class="card-text">Prepara tus platos favoritos con setas con la tranquilidad de saber que su consumo está totalmente indicado.</p>
              </div>
            </div>
          </div>
    </div>

</div>

  
{% endblock %}

mushwebapp/mushinfo/templates/mushinfo_page.html
{% extends "base_tmplt.html" %}

{% load static %}

{% block extrahead %}

  <link rel="stylesheet" href="{% static '/css/basestyle.css' %}">

{% endblock %}

{% block body %}

<div class="container">

    <h1>Información general y datos</h1>

    <div class="row g-0 border rounded overflow-hidden flex-md-row  shadow-sm  position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block">Setas en España</strong>
          <div class="mb-1 text-muted">Las mejores zonas para la recolección</div>
          <p class="card-text mb-auto">La red de sociedades micológicas nacionales cumplen una gran labor divulgativa con la intención de evitar 
              ingestas accidentales por confusión entre especies. Henar Roldán, bióloga investigadora del CSIC, recuerda que "todas las setas son 
              comestibles, pero algunas una sola vez". Si existe duda al identificar un ejemplar, es mejor descartarlo. Roldán señala también que es 
              necesario un cambio de mentalidad: "Hay que salir al campo para encontrar e identificar setas, sin cogerlas". Una recomendación que en 
              caso de espacios protegidos es una obligación legal: está prohibido dañar la flora y la fauna. </p>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img class="" src="https://e00-expansion.uecdn.es/assets/multimedia/imagenes/2017/11/14/15106532948180.jpg" alt="Card image cap" width="700" height="400">
        </div>
    </div>
    <hr>
    <hr>
    <div class="row g-0 border rounded overflow-hidden flex-md-row  shadow-sm  position-relative">
        <div class="col-auto d-none d-lg-block">
            <img class="" src="https://www.tribunasalamanca.com/images/images/setas%281%29.jpg" alt="Card image cap" width="700" height="450">
        </div>
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block">World</strong>
          <h3 class="mb-0">Featured post</h3>
          <div class="mb-1 text-muted">Nov 12</div>
          <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
        </div>
    </div>
    <hr>
    <hr>
    <div class="row g-0 border rounded overflow-hidden flex-md-row  shadow-sm  position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block">World</strong>
          <h3 class="mb-0">Featured post</h3>
          <div class="mb-1 text-muted">Nov 12</div>
          <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img class="" src="https://www.tribunasalamanca.com/images/images/setas%281%29.jpg" alt="Card image cap" width="700" height="450">
        </div>
    </div>
    <hr>
    <hr>
    <div class="row g-0 border rounded overflow-hidden flex-md-row  shadow-sm  position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block">World</strong>
          <h3 class="mb-0">Featured post</h3>
          <div class="mb-1 text-muted">Nov 12</div>
          <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img class="" src="https://www.tribunasalamanca.com/images/images/setas%281%29.jpg" alt="Card image cap" width="350" height="300">
        </div>
        <div class="col-auto d-none d-lg-block">
            <img class="" src="https://www.tribunasalamanca.com/images/images/setas%281%29.jpg" alt="Card image cap" width="350" height="300">
        </div>
    </div>

</div>

  
{% endblock %}

mushwebapp/templates/base_tmplt.html
<!DOCTYPE html>

{% load static %}

<html lang="es">
    <head>

        <title>Clasificador de setas</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'css/basestyle.css' %}" type="text/css">

        {% block extrahead %}

        {% endblock %}

    </head>


    <body>
        <header>
            
            <nav class="navbar navbar-expand-md" style="background-color: #69744c;">
                <div class="container-fluid">
                    <a href="{% url 'landing:landing' %}" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
                        <img src="https://www.freeiconspng.com/uploads/mushroom-icon-29.png" class="mushhAPPicon" alt="mario icon" width="75" height="75">
                    </a>

                    <div class="navbar-collapse collapse" id="collapseNavbar">
                        <ul class="navbar-nav ms-auto">
                            <li>
                                <a href="{% url 'landing:landing' %}" class="nav-link text-white">
                                  <i class="bi-house-fill d-block mx-auto mb-1" style="font-size: 2rem; color: white; text-align: center"></i>
                                  Home
                                </a>
                              </li>
                              <li>
                                <a href="https://kschool.com/" class="nav-link text-white">
                                  <i class="bi bi-journal-code d-block mx-auto mb-1" style="font-size: 2rem; color: white; text-align: center"></i>
                                  KSchool
                                  
                                </a>
                              </li>
                              <li>
                                <a href="https://github.com/pablovillabay/mushrooms-PFM" class="nav-link text-white">
                                  <i class="bi-github d-block mx-auto mb-1" style="font-size: 2rem; color: white; text-align: center"></i>
                                  Github
                                </a>
                              </li>
                        </ul>
                    </div>
                </div>
            </nav>

        </header>

        <div class="wrapper">

            <nav id="sidebar">
                <div class="sidebar-header">
                    <h3>mushAPP</h3>
                </div>

                <ul class="components"> 
                    <li>
                        <li>
                            <a href="{% url 'mushinfo:mushinfo' %}">
                                <i class="bi bi-info-square"></i>
                                Información
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'dataclass:dataclass' %}">
                                <i class="bi bi-bar-chart-line"></i>
                                Data-Class
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'imgclass:imgclass' %}">
                                <i class="bi bi-image"></i>
                                IMG-Class
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="bi bi-people"></i>
                                Sobre nosotros
                            </a>
                        </li>
                    </li>
                </ul>
            </nav>

            <div id="content">              

                {% block body %}


                {% endblock %} 
                       
            </div>
        </div>


        <footer class="page-footer grey darken-4">
            <div class="container grey darken-2">
              <h5 style="color:white;">Clasificador de setas</h5>
              <p style="color:white;">Proyecto de fin de máster para la consecución del Máster en Ciencia de Datos 
                  de KSchool en la modalidad online, edición 2021/2022</p>
            </div>
            <div class="footer-copyright grey darken-3">
              <div class="container">
                <p style="color:white;">PFM Grupo-A</p>
              </div>
      
            </div>
        </footer>


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </body>

</html>